// Generated by scripts/prepare-brand.mjs from the supplied PNG silhouette.
// Replace with the original brand SVG path when that source becomes available.
export const NALT_A_VIEWBOX = "0 0 663 481";
export const NALT_A_PATH = "M332 0L663 481L562 480L333 143L102 478L0 480Z";
