import fs from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

// Asset conversion only: the A contour comes from the supplied pixels, not a newly designed polygon.
const sourceDirectory = process.argv[2];
if (!sourceDirectory) throw new Error("Provide the folder containing wordmark_nalt.png and facivon_nalt.png.");
const output = path.resolve("public/brand");
await fs.mkdir(path.join(output, "originals"), { recursive: true });
for (const name of ["wordmark_nalt.png", "facivon_nalt.png"]) {
  await fs.copyFile(path.join(sourceDirectory, name), path.join(output, "originals", name));
}

const source = path.join(sourceDirectory, "facivon_nalt.png");
const { data, info } = await sharp(source).removeAlpha().raw().toBuffer({ resolveWithObject: true });
const inside = (x, y) => {
  if (x < 0 || y < 0 || x >= info.width || y >= info.height) return false;
  const i = (y * info.width + x) * info.channels;
  return data[i] > 150 && data[i] > data[i + 1] * 2.2 && data[i + 1] > 20;
};
const edges = new Map();
const key = (x, y) => `${x},${y}`;
const add = (x1, y1, x2, y2) => edges.set(key(x1, y1), [x2, y2]);
let bounds = { left: info.width, top: info.height, right: 0, bottom: 0 };
for (let y = 0; y < info.height; y++) {
  for (let x = 0; x < info.width; x++) {
    if (!inside(x, y)) continue;
    bounds.left = Math.min(bounds.left, x);
    bounds.top = Math.min(bounds.top, y);
    bounds.right = Math.max(bounds.right, x + 1);
    bounds.bottom = Math.max(bounds.bottom, y + 1);
    if (!inside(x, y - 1)) add(x, y, x + 1, y);
    if (!inside(x + 1, y)) add(x + 1, y, x + 1, y + 1);
    if (!inside(x, y + 1)) add(x + 1, y + 1, x, y + 1);
    if (!inside(x - 1, y)) add(x, y + 1, x, y);
  }
}
const contours = [];
while (edges.size) {
  const start = edges.keys().next().value;
  let cursor = start;
  const points = [];
  while (edges.has(cursor)) {
    const [x, y] = cursor.split(",").map(Number);
    points.push([x - bounds.left, y - bounds.top]);
    const next = edges.get(cursor);
    edges.delete(cursor);
    cursor = key(...next);
    if (cursor === start) break;
  }
  contours.push(points);
}
const contour = contours.sort((a, b) => b.length - a.length)[0];
if (!contour || contour.length < 20) throw new Error("Could not find the supplied A silhouette.");

function simplify(points, tolerance) {
  if (points.length < 3) return points;
  const [ax, ay] = points[0];
  const [bx, by] = points.at(-1);
  const dx = bx - ax;
  const dy = by - ay;
  let maximum = 0;
  let split = 0;
  for (let i = 1; i < points.length - 1; i++) {
    const [px, py] = points[i];
    const t = dx || dy ? Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy))) : 0;
    const distance = Math.hypot(px - ax - t * dx, py - ay - t * dy);
    if (distance > maximum) { maximum = distance; split = i; }
  }
  if (maximum <= tolerance) return [points[0], points.at(-1)];
  return [...simplify(points.slice(0, split + 1), tolerance).slice(0, -1), ...simplify(points.slice(split), tolerance)];
}
// Up to two source pixels (0.3% of the mark width) remove raster texture and staircase artifacts.
// All resulting vertices are selected from the supplied contour; none are manually redrawn.
const tolerance = 2;
const points = simplify([...contour, contour[0]], tolerance).slice(0, -1);
const width = bounds.right - bounds.left;
const height = bounds.bottom - bounds.top;
const geometry = `M${points.map((point) => point.join(" ")).join("L")}Z`;
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}"><path fill="#ff4b00" d="${geometry}"/></svg>\n`;
await fs.writeFile(path.join(output, "nalt-a.svg"), `<!-- Faithfully traced from supplied facivon_nalt.png; not an original brand SVG. -->\n${svg}`);
await fs.writeFile(path.join(output, "nalt-icon.svg"), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 720"><path fill="#080808" d="M0 0h720v720H0z"/><path fill="#ff4b00" transform="translate(50 ${Math.round((720 - height * 620 / width) / 2)}) scale(${620 / width})" d="${geometry}"/></svg>\n`);
await fs.mkdir("lib/brand", { recursive: true });
await fs.writeFile("lib/brand/naltGeometry.ts", `// Generated by scripts/prepare-brand.mjs from the supplied PNG silhouette.\n// Replace with the original brand SVG path when that source becomes available.\nexport const NALT_A_VIEWBOX = "0 0 ${width} ${height}";\nexport const NALT_A_PATH = "${geometry}";\n`);

async function cropWordmark(name, region) {
  const { data: pixels, info: imageInfo } = await sharp(path.join(sourceDirectory, "wordmark_nalt.png"))
    .extract(region).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  for (let i = 0; i < pixels.length; i += 4) {
    const peak = Math.max(pixels[i], pixels[i + 1], pixels[i + 2]);
    const alpha = Math.min(1, Math.max(0, (peak - 8) / 32));
    pixels[i + 3] = Math.round(alpha * 255);
  }
  await sharp(pixels, { raw: imageInfo }).png().toFile(path.join(output, name));
}
await cropWordmark("nalt-wordmark.png", { left: 529, top: 217, width: 1075, height: 235 });
await cropWordmark("nalt-n.png", { left: 529, top: 225, width: 247, height: 227 });
await cropWordmark("nalt-l.png", { left: 1176, top: 225, width: 184, height: 227 });
await cropWordmark("nalt-t.png", { left: 1368, top: 225, width: 236, height: 227 });
await sharp(path.join(output, "nalt-icon.svg")).resize(180, 180).png().toFile(path.join(output, "apple-touch-icon.png"));
console.log(JSON.stringify({ source: "facivon_nalt.png", bounds, width, height, contourPoints: points.length, toleranceInSourcePixels: tolerance }));
